// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRl4lJDyw5I5kgOulqrGMtexKaamm9u08',
    appId: '1:915486119537:android:4e9c8d644893125275edd0',
    messagingSenderId: '915486119537',
    projectId: 'studenttimetable-b1778',
    storageBucket: 'studenttimetable-b1778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDthuKpnoTiyswM3oa5DfvktBFPrB3aDJU',
    appId: '1:915486119537:ios:3dffaaac7242ace275edd0',
    messagingSenderId: '915486119537',
    projectId: 'studenttimetable-b1778',
    storageBucket: 'studenttimetable-b1778.firebasestorage.app',
    iosBundleId: 'com.example.studenttimetableapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIajnQx9_RsbBeIgopnCdcl26GVZUyujo',
    appId: '1:915486119537:web:4db0aa39d2ac179475edd0',
    messagingSenderId: '915486119537',
    projectId: 'studenttimetable-b1778',
    authDomain: 'studenttimetable-b1778.firebaseapp.com',
    storageBucket: 'studenttimetable-b1778.firebasestorage.app',
  );
}
